language: node_js
node_js:
 - "node"
after_success:
 - npm run doc
cache:
  npm: true
  directories:
    - node_modules
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: docs
    on:
      tags: false
      branch: feature/docs
      node_js: "node"
